// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEEzUgpuwHiWk40VGtIxeWCaL3S7vbuA',
    appId: '1:855638988514:web:0d396f590dbf3b939970bb',
    messagingSenderId: '855638988514',
    projectId: 'chat-app-a867e',
    authDomain: 'chat-app-a867e.firebaseapp.com',
    storageBucket: 'chat-app-a867e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdRR8CrJYIW-DSDZ3le24EdBr2-EspqYg',
    appId: '1:855638988514:android:d396fa8c8f9d895e9970bb',
    messagingSenderId: '855638988514',
    projectId: 'chat-app-a867e',
    storageBucket: 'chat-app-a867e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCNCdg77YIpTQzRa-6iKEYtrM-WCoCXk',
    appId: '1:855638988514:ios:999b5ad65ec9af479970bb',
    messagingSenderId: '855638988514',
    projectId: 'chat-app-a867e',
    storageBucket: 'chat-app-a867e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCNCdg77YIpTQzRa-6iKEYtrM-WCoCXk',
    appId: '1:855638988514:ios:999b5ad65ec9af479970bb',
    messagingSenderId: '855638988514',
    projectId: 'chat-app-a867e',
    storageBucket: 'chat-app-a867e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKEEzUgpuwHiWk40VGtIxeWCaL3S7vbuA',
    appId: '1:855638988514:web:5f1ecd5b8dc6d16a9970bb',
    messagingSenderId: '855638988514',
    projectId: 'chat-app-a867e',
    authDomain: 'chat-app-a867e.firebaseapp.com',
    storageBucket: 'chat-app-a867e.firebasestorage.app',
  );
}
